<!-- https://mdsvex.pngwn.io/docs/#layout -->
<!-- Replace HTML tags generated by "mdsvex" with custom ones -->

<script lang="ts" context="module">
	import { img, a } from '$lib/components/custom';
	export { img, a };
</script>

<slot />
